#!/usr/bin/env bash
# Build the Cursor plugin tree and deploy it to its generated distribution repo.
set -euo pipefail

: "${DIST_REPO:?set DIST_REPO=<git-url|owner/name> (usually via PUBLISH_TARGETS)}"
SRC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SLUG="$(printf '%s' "$DIST_REPO" | sed -E 's#^git@[^:]+:##; s#^https?://[^/]+/##; s#\.git$##')"
case "$DIST_REPO" in
  *://*|*@*) CLONE_URL="$DIST_REPO" ;;
  *)
    if [[ -n "${GH_TOKEN:-}" ]]; then
      CLONE_URL="https://x-access-token:${GH_TOKEN}@github.com/${DIST_REPO}.git"
    else
      CLONE_URL="https://github.com/${DIST_REPO}.git"
    fi
    ;;
esac

WORKTREE="$(mktemp -d)/dist"
trap 'rm -rf "$(dirname "$WORKTREE")"' EXIT
echo "==> Cloning $SLUG"
git clone --depth 1 "$CLONE_URL" "$WORKTREE" 2>/dev/null \
  || git clone "$CLONE_URL" "$WORKTREE"

# The first migration starts from the reviewed extension tree. Subsequent
# deployments may replace only commits generated by this publisher. A direct
# edit to the distribution repository needs to be brought into this monorepo
# before the next release.
MIGRATION_SHA="f7d7e7d4170aba829374f93e236c70f76b544eaf"
CURRENT_SHA="$(git -C "$WORKTREE" rev-parse HEAD)"
CURRENT_SUBJECT="$(git -C "$WORKTREE" log -1 --format=%s)"
if [[ "$SLUG" == "braintrustdata/braintrust-cursor-extension" ]] \
  && [[ "$CURRENT_SHA" != "$MIGRATION_SHA" ]] \
  && [[ "$CURRENT_SUBJECT" != "build: deploy cursor plugin from monorepo@"* ]]; then
  echo "error: $SLUG has direct changes at $CURRENT_SHA; copy them into src/plugins/cursor/content before publishing." >&2
  exit 1
fi
git -C "$WORKTREE" config user.name "github-actions[bot]"
git -C "$WORKTREE" config user.email "41898282+github-actions[bot]@users.noreply.github.com"

echo "==> Rebuilding Cursor plugin tree"
git -C "$WORKTREE" rm -rfq --ignore-unmatch . >/dev/null 2>&1 || true
"$SRC_DIR/build.sh" "$WORKTREE"
"$SRC_DIR/validate.sh" "$WORKTREE"
git -C "$WORKTREE" add -A
if git -C "$WORKTREE" diff --cached --quiet; then
  echo "==> $SLUG already up to date; nothing to publish."
  exit 0
fi

SRC_SHA="$(git -C "$SRC_DIR" rev-parse --short HEAD 2>/dev/null || echo unknown)"
git -C "$WORKTREE" commit -q -m "build: deploy cursor plugin from monorepo@${SRC_SHA}"
if [[ "${DRY_RUN:-}" == "1" ]]; then
  echo "==> DRY_RUN=1: built + committed locally, skipping push."
  git -C "$WORKTREE" --no-pager show --stat HEAD | head -30
  exit 0
fi
echo "==> Pushing to $SLUG (main)"
git -C "$WORKTREE" push origin HEAD:main
echo "==> Deployed Cursor plugin to $SLUG."
